# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'challenges_selector.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 768)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(180, 15, 831, 111))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.challengesLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(36)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.challengesLabel.setFont(font)
        self.challengesLabel.setAutoFillBackground(False)
        self.challengesLabel.setStyleSheet("QLabel {\n"
"    border: 2px solid;\n"
"    border-radius: 8px;\n"
"    background-color: #73d7ff;\n"
"}")
        self.challengesLabel.setScaledContents(True)
        self.challengesLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.challengesLabel.setWordWrap(True)
        self.challengesLabel.setObjectName("challengesLabel")
        self.verticalLayout_2.addWidget(self.challengesLabel)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 0, 1024, 768))
        self.frame.setStyleSheet("QFrame {\n"
"    background-color: #ccfcff\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.backButton = QtWidgets.QPushButton(self.frame)
        self.backButton.setGeometry(QtCore.QRect(10, 20, 141, 101))
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(48)
        self.backButton.setFont(font)
        self.backButton.setStyleSheet("QPushButton {\n"
"    border: 2px solid;\n"
"    border-radius: 8px;\n"
"    background-color: #a1e4ff;\n"
"}")
        self.backButton.setCheckable(True)
        self.backButton.setObjectName("backButton")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 140, 991, 571))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.chal1Button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.chal1Button.setFont(font)
        self.chal1Button.setAutoFillBackground(False)
        self.chal1Button.setStyleSheet("QPushButton {\n"
"    border: 2px solid;\n"
"    border-radius: 8px;\n"
"    background-color:#b0e8ff;\n"
"}")
        self.chal1Button.setCheckable(True)
        self.chal1Button.setAutoDefault(False)
        self.chal1Button.setDefault(True)
        self.chal1Button.setFlat(False)
        self.chal1Button.setObjectName("chal1Button")
        self.verticalLayout.addWidget(self.chal1Button)
        self.chal2Button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(20)
        self.chal2Button.setFont(font)
        self.chal2Button.setAutoFillBackground(False)
        self.chal2Button.setStyleSheet("QPushButton {\n"
"    border: 2px solid;\n"
"    border-radius: 8px;\n"
"    background-color: #8cdeff;\n"
"}")
        self.chal2Button.setCheckable(True)
        self.chal2Button.setDefault(True)
        self.chal2Button.setObjectName("chal2Button")
        self.verticalLayout.addWidget(self.chal2Button)
        self.chal3Button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(20)
        self.chal3Button.setFont(font)
        self.chal3Button.setAutoFillBackground(False)
        self.chal3Button.setStyleSheet("QPushButton {\n"
"    border: 2px solid;\n"
"    border-radius: 8px;\n"
"    background-color:#b0e8ff;\n"
"}")
        self.chal3Button.setCheckable(True)
        self.chal3Button.setDefault(True)
        self.chal3Button.setObjectName("chal3Button")
        self.verticalLayout.addWidget(self.chal3Button)
        self.chal4Button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(20)
        self.chal4Button.setFont(font)
        self.chal4Button.setAutoFillBackground(False)
        self.chal4Button.setStyleSheet("QPushButton {\n"
"    border: 2px solid;\n"
"    border-radius: 8px;\n"
"    background-color: #8cdeff;\n"
"}")
        self.chal4Button.setCheckable(True)
        self.chal4Button.setDefault(True)
        self.chal4Button.setObjectName("chal4Button")
        self.verticalLayout.addWidget(self.chal4Button)
        self.chal5Button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(20)
        self.chal5Button.setFont(font)
        self.chal5Button.setAutoFillBackground(False)
        self.chal5Button.setStyleSheet("QPushButton {\n"
"    border: 2px solid;\n"
"    border-radius: 8px;\n"
"    background-color:#b0e8ff;\n"
"}")
        self.chal5Button.setCheckable(True)
        self.chal5Button.setDefault(True)
        self.chal5Button.setObjectName("chal5Button")
        self.verticalLayout.addWidget(self.chal5Button)
        self.chal6Button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(20)
        self.chal6Button.setFont(font)
        self.chal6Button.setAutoFillBackground(False)
        self.chal6Button.setStyleSheet("QPushButton {\n"
"    border: 2px solid;\n"
"    border-radius: 8px;\n"
"    background-color: #8cdeff;\n"
"}")
        self.chal6Button.setCheckable(True)
        self.chal6Button.setDefault(True)
        self.chal6Button.setObjectName("chal6Button")
        self.verticalLayout.addWidget(self.chal6Button)
        self.chal7Button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(20)
        self.chal7Button.setFont(font)
        self.chal7Button.setAutoFillBackground(False)
        self.chal7Button.setStyleSheet("QPushButton {\n"
"    border: 2px solid;\n"
"    border-radius: 8px;\n"
"    background-color:#b0e8ff;\n"
"}")
        self.chal7Button.setCheckable(True)
        self.chal7Button.setDefault(True)
        self.chal7Button.setObjectName("chal7Button")
        self.verticalLayout.addWidget(self.chal7Button)
        self.chal8Button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(20)
        self.chal8Button.setFont(font)
        self.chal8Button.setAutoFillBackground(False)
        self.chal8Button.setStyleSheet("QPushButton {\n"
"    border: 2px solid;\n"
"    border-radius: 8px;\n"
"    background-color: #8cdeff;\n"
"}")
        self.chal8Button.setCheckable(True)
        self.chal8Button.setDefault(True)
        self.chal8Button.setObjectName("chal8Button")
        self.verticalLayout.addWidget(self.chal8Button)
        self.chal9Button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(20)
        self.chal9Button.setFont(font)
        self.chal9Button.setAutoFillBackground(False)
        self.chal9Button.setStyleSheet("QPushButton {\n"
"    border: 2px solid;\n"
"    border-radius: 8px;\n"
"    background-color:#b0e8ff;\n"
"}")
        self.chal9Button.setCheckable(True)
        self.chal9Button.setDefault(True)
        self.chal9Button.setObjectName("chal9Button")
        self.verticalLayout.addWidget(self.chal9Button)
        self.extensionButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(20)
        self.extensionButton.setFont(font)
        self.extensionButton.setAutoFillBackground(False)
        self.extensionButton.setStyleSheet("QPushButton {\n"
"    border: 2px solid;\n"
"    border-radius: 8px;\n"
"    background-color: #8cdeff;\n"
"}")
        self.extensionButton.setCheckable(True)
        self.extensionButton.setDefault(True)
        self.extensionButton.setObjectName("extensionButton")
        self.verticalLayout.addWidget(self.extensionButton)
        self.frame.raise_()
        self.verticalLayoutWidget_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.challengesLabel.setText(_translate("MainWindow", "Challenges"))
        self.backButton.setText(_translate("MainWindow", "<"))
        self.chal1Button.setText(_translate("MainWindow", "1: Simple Model"))
        self.chal2Button.setText(_translate("MainWindow", "2: Analytic Model"))
        self.chal3Button.setText(_translate("MainWindow", "3: \"Low Ball\" and \"High Ball\" Trajectories"))
        self.chal4Button.setText(_translate("MainWindow", "4: Maximising Horizontal Range"))
        self.chal5Button.setText(_translate("MainWindow", "5: Bounding Parabola"))
        self.chal6Button.setText(_translate("MainWindow", "6: Maximising Horizontal Range and Calculating Distance"))
        self.chal7Button.setText(_translate("MainWindow", "7: Projectile Range Against Time"))
        self.chal8Button.setText(_translate("MainWindow", "8: Trajectory with Bounces"))
        self.chal9Button.setText(_translate("MainWindow", "9: Model Incorporating Air Resistance"))
        self.extensionButton.setText(_translate("MainWindow", "Extension: Satellite Orbitting a Spherical Planet"))
