# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'challenge2.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 768)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1024, 768))
        self.frame.setStyleSheet("QFrame {\n"
"    background-color: #ccfcff\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.backButton = QtWidgets.QPushButton(self.frame)
        self.backButton.setGeometry(QtCore.QRect(30, 20, 131, 101))
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(24)
        self.backButton.setFont(font)
        self.backButton.setStyleSheet("QPushButton {\n"
"    border: 2px solid;\n"
"    border-radius: 8px;\n"
"    background-color: #a1e4ff;\n"
"}")
        self.backButton.setCheckable(True)
        self.backButton.setObjectName("backButton")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(570, 160, 201, 561))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.inputLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.inputLayout.setContentsMargins(0, 0, 0, 0)
        self.inputLayout.setSpacing(5)
        self.inputLayout.setObjectName("inputLayout")
        self.textModeCheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(11)
        self.textModeCheckBox.setFont(font)
        self.textModeCheckBox.setObjectName("textModeCheckBox")
        self.inputLayout.addWidget(self.textModeCheckBox)
        self.Line1 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.Line1.setStyleSheet("QFrame {\n"
"    background-color: #838285;\n"
"    min-height:1px;\n"
"    max-height:1px;\n"
"}")
        self.Line1.setFrameShape(QtWidgets.QFrame.HLine)
        self.Line1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Line1.setObjectName("Line1")
        self.inputLayout.addWidget(self.Line1)
        self.launchSpeedLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.launchSpeedLabel.setFont(font)
        self.launchSpeedLabel.setStyleSheet("QLabel {background-color: #a1e4ff;}")
        self.launchSpeedLabel.setObjectName("launchSpeedLabel")
        self.inputLayout.addWidget(self.launchSpeedLabel)
        self.launchSpeedSlider = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.launchSpeedSlider.setStyleSheet("QSlider::groove:horizontal {border: 1px solid #3256a8;\n"
"height: 8px;\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #85c8f2, stop: 1 #1293e3);}\n"
"\n"
"QSlider::handle:horizontal {border: 1px solid #3256a8;\n"
"background: #073191;\n"
"width: 10px;\n"
"height: 10px;\n"
"border-radius: 5px;}")
        self.launchSpeedSlider.setOrientation(QtCore.Qt.Horizontal)
        self.launchSpeedSlider.setObjectName("launchSpeedSlider")
        self.inputLayout.addWidget(self.launchSpeedSlider)
        self.launchSpeedSliderLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(10)
        self.launchSpeedSliderLabel.setFont(font)
        self.launchSpeedSliderLabel.setStyleSheet("QLabel {background-color: #a1e4ff;}")
        self.launchSpeedSliderLabel.setText("")
        self.launchSpeedSliderLabel.setObjectName("launchSpeedSliderLabel")
        self.inputLayout.addWidget(self.launchSpeedSliderLabel)
        self.launchSpeedLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.launchSpeedLineEdit.setFont(font)
        self.launchSpeedLineEdit.setInputMask("")
        self.launchSpeedLineEdit.setObjectName("launchSpeedLineEdit")
        self.inputLayout.addWidget(self.launchSpeedLineEdit)
        self.Line2 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.Line2.setStyleSheet("QFrame {\n"
"    background-color: #838285;\n"
"    min-height:1px;\n"
"    max-height:1px;\n"
"}")
        self.Line2.setFrameShape(QtWidgets.QFrame.HLine)
        self.Line2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Line2.setObjectName("Line2")
        self.inputLayout.addWidget(self.Line2)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel {background-color: #a1e4ff;}")
        self.label_3.setObjectName("label_3")
        self.inputLayout.addWidget(self.label_3)
        self.launchAngleSlider = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.launchAngleSlider.setStyleSheet("QSlider::groove:horizontal {border: 1px solid #3256a8;\n"
"height: 8px;\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #85c8f2, stop: 1 #1293e3);}\n"
"\n"
"QSlider::handle:horizontal {border: 1px solid #3256a8;\n"
"background: #073191;\n"
"width: 10px;\n"
"height: 10px;\n"
"border-radius: 5px;}")
        self.launchAngleSlider.setOrientation(QtCore.Qt.Horizontal)
        self.launchAngleSlider.setObjectName("launchAngleSlider")
        self.inputLayout.addWidget(self.launchAngleSlider)
        self.launchAngleSliderLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(10)
        self.launchAngleSliderLabel.setFont(font)
        self.launchAngleSliderLabel.setStyleSheet("QLabel {background-color: #a1e4ff;}")
        self.launchAngleSliderLabel.setText("")
        self.launchAngleSliderLabel.setObjectName("launchAngleSliderLabel")
        self.inputLayout.addWidget(self.launchAngleSliderLabel)
        self.launchAngleLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.launchAngleLineEdit.setFont(font)
        self.launchAngleLineEdit.setObjectName("launchAngleLineEdit")
        self.inputLayout.addWidget(self.launchAngleLineEdit)
        self.Line3 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.Line3.setStyleSheet("QFrame {\n"
"    background-color: #838285;\n"
"    min-height:1px;\n"
"    max-height:1px;\n"
"}")
        self.Line3.setFrameShape(QtWidgets.QFrame.HLine)
        self.Line3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Line3.setObjectName("Line3")
        self.inputLayout.addWidget(self.Line3)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel {background-color: #a1e4ff;}")
        self.label_4.setObjectName("label_4")
        self.inputLayout.addWidget(self.label_4)
        self.setgButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(9)
        self.setgButton.setFont(font)
        self.setgButton.setStyleSheet("QPushButton {\n"
"    border: 1px solid;\n"
"    border-radius: 4px;\n"
"    background-color:#b1defa;\n"
"}")
        self.setgButton.setObjectName("setgButton")
        self.inputLayout.addWidget(self.setgButton)
        self.gSlider = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.gSlider.setStyleSheet("QSlider::groove:horizontal {border: 1px solid #3256a8;\n"
"height: 8px;\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #85c8f2, stop: 1 #1293e3);}\n"
"\n"
"QSlider::handle:horizontal {border: 1px solid #3256a8;\n"
"background: #073191;\n"
"width: 10px;\n"
"height: 10px;\n"
"border-radius: 5px;}")
        self.gSlider.setOrientation(QtCore.Qt.Horizontal)
        self.gSlider.setObjectName("gSlider")
        self.inputLayout.addWidget(self.gSlider)
        self.gSliderLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(10)
        self.gSliderLabel.setFont(font)
        self.gSliderLabel.setStyleSheet("QLabel {background-color: #a1e4ff;}")
        self.gSliderLabel.setText("")
        self.gSliderLabel.setObjectName("gSliderLabel")
        self.inputLayout.addWidget(self.gSliderLabel)
        self.gLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.gLineEdit.setFont(font)
        self.gLineEdit.setObjectName("gLineEdit")
        self.inputLayout.addWidget(self.gLineEdit)
        self.Line4 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.Line4.setStyleSheet("QFrame {\n"
"    background-color: #838285;\n"
"    min-height:1px;\n"
"    max-height:1px;\n"
"}")
        self.Line4.setFrameShape(QtWidgets.QFrame.HLine)
        self.Line4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Line4.setObjectName("Line4")
        self.inputLayout.addWidget(self.Line4)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("QLabel {background-color: #a1e4ff;}")
        self.label_5.setObjectName("label_5")
        self.inputLayout.addWidget(self.label_5)
        self.launchHeightSlider = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.launchHeightSlider.setStyleSheet("QSlider::groove:horizontal {border: 1px solid #3256a8;\n"
"height: 8px;\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #85c8f2, stop: 1 #1293e3);}\n"
"\n"
"QSlider::handle:horizontal {border: 1px solid #3256a8;\n"
"background: #073191;\n"
"width: 10px;\n"
"height: 10px;\n"
"border-radius: 5px;}")
        self.launchHeightSlider.setOrientation(QtCore.Qt.Horizontal)
        self.launchHeightSlider.setObjectName("launchHeightSlider")
        self.inputLayout.addWidget(self.launchHeightSlider)
        self.launchHeightSliderLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(10)
        self.launchHeightSliderLabel.setFont(font)
        self.launchHeightSliderLabel.setStyleSheet("QLabel {background-color: #a1e4ff;}")
        self.launchHeightSliderLabel.setText("")
        self.launchHeightSliderLabel.setObjectName("launchHeightSliderLabel")
        self.inputLayout.addWidget(self.launchHeightSliderLabel)
        self.launchHeightLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.launchHeightLineEdit.setFont(font)
        self.launchHeightLineEdit.setObjectName("launchHeightLineEdit")
        self.inputLayout.addWidget(self.launchHeightLineEdit)
        self.Line5 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.Line5.setStyleSheet("QFrame {\n"
"    background-color: #838285;\n"
"    min-height:1px;\n"
"    max-height:1px;\n"
"}")
        self.Line5.setFrameShape(QtWidgets.QFrame.HLine)
        self.Line5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Line5.setObjectName("Line5")
        self.inputLayout.addWidget(self.Line5)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("QLabel {background-color: #a1e4ff;}")
        self.label_6.setObjectName("label_6")
        self.inputLayout.addWidget(self.label_6)
        self.timeStepSlider = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.timeStepSlider.setStyleSheet("QSlider::groove:horizontal {border: 1px solid #3256a8;\n"
"height: 8px;\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #85c8f2, stop: 1 #1293e3);}\n"
"\n"
"QSlider::handle:horizontal {border: 1px solid #3256a8;\n"
"background: #073191;\n"
"width: 10px;\n"
"height: 10px;\n"
"border-radius: 5px;}")
        self.timeStepSlider.setOrientation(QtCore.Qt.Horizontal)
        self.timeStepSlider.setObjectName("timeStepSlider")
        self.inputLayout.addWidget(self.timeStepSlider)
        self.timeStepSliderLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(10)
        self.timeStepSliderLabel.setFont(font)
        self.timeStepSliderLabel.setStyleSheet("QLabel {background-color: #a1e4ff;}")
        self.timeStepSliderLabel.setText("")
        self.timeStepSliderLabel.setObjectName("timeStepSliderLabel")
        self.inputLayout.addWidget(self.timeStepSliderLabel)
        self.timeStepLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.timeStepLineEdit.setFont(font)
        self.timeStepLineEdit.setObjectName("timeStepLineEdit")
        self.inputLayout.addWidget(self.timeStepLineEdit)
        self.inputLayout.setStretch(2, 1)
        self.inputLayout.setStretch(3, 1)
        self.inputLayout.setStretch(7, 1)
        self.inputLayout.setStretch(8, 2)
        self.inputLayout.setStretch(12, 1)
        self.inputLayout.setStretch(14, 1)
        self.inputLayout.setStretch(18, 1)
        self.inputLayout.setStretch(19, 1)
        self.inputLayout.setStretch(23, 1)
        self.inputLayout.setStretch(24, 1)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(30, 150, 521, 461))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.graphLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.graphLayout.setContentsMargins(0, 0, 0, 0)
        self.graphLayout.setObjectName("graphLayout")
        self.infoButton = QtWidgets.QPushButton(self.frame)
        self.infoButton.setGeometry(QtCore.QRect(870, 20, 131, 101))
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(24)
        self.infoButton.setFont(font)
        self.infoButton.setStyleSheet("QPushButton {\n"
"    border: 2px solid;\n"
"    border-radius: 8px;\n"
"    background-color: #a1e4ff;\n"
"}")
        self.infoButton.setCheckable(True)
        self.infoButton.setObjectName("infoButton")
        self.listWidget = QtWidgets.QListWidget(self.frame)
        self.listWidget.setGeometry(QtCore.QRect(740, 230, 261, 501))
        self.listWidget.setStyleSheet("QWidget {\n"
"    border-radius: 8px;\n"
"    background-color: #a1e4ff;\n"
"}")
        self.listWidget.setObjectName("listWidget")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(180, 10, 671, 121))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.challengeTitleLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.challengeTitleLabel.setFont(font)
        self.challengeTitleLabel.setAutoFillBackground(False)
        self.challengeTitleLabel.setStyleSheet("QLabel {\n"
"    border: 2px solid;\n"
"    border-radius: 8px;\n"
"    background-color: #73d7ff;\n"
"}")
        self.challengeTitleLabel.setScaledContents(True)
        self.challengeTitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.challengeTitleLabel.setWordWrap(True)
        self.challengeTitleLabel.setObjectName("challengeTitleLabel")
        self.verticalLayout_2.addWidget(self.challengeTitleLabel)
        self.analyticsListWidget = QtWidgets.QListWidget(self.frame)
        self.analyticsListWidget.setGeometry(QtCore.QRect(30, 620, 521, 111))
        self.analyticsListWidget.setStyleSheet("QWidget {\n"
"    border-radius: 8px;\n"
"    background-color: #a1e4ff;\n"
"}")
        self.analyticsListWidget.setObjectName("analyticsListWidget")
        self.rangeLabel = QtWidgets.QLabel(self.frame)
        self.rangeLabel.setGeometry(QtCore.QRect(40, 650, 251, 21))
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.rangeLabel.setFont(font)
        self.rangeLabel.setStyleSheet("QLabel {background-color: #a1e4ff;}")
        self.rangeLabel.setObjectName("rangeLabel")
        self.apogeeLabel = QtWidgets.QLabel(self.frame)
        self.apogeeLabel.setGeometry(QtCore.QRect(40, 680, 261, 21))
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.apogeeLabel.setFont(font)
        self.apogeeLabel.setStyleSheet("QLabel {background-color: #a1e4ff;}")
        self.apogeeLabel.setObjectName("apogeeLabel")
        self.flightTimeLabel = QtWidgets.QLabel(self.frame)
        self.flightTimeLabel.setGeometry(QtCore.QRect(40, 710, 251, 21))
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.flightTimeLabel.setFont(font)
        self.flightTimeLabel.setStyleSheet("QLabel {background-color: #a1e4ff;}")
        self.flightTimeLabel.setObjectName("flightTimeLabel")
        self.listWidget_2 = QtWidgets.QListWidget(self.frame)
        self.listWidget_2.setGeometry(QtCore.QRect(560, 150, 221, 581))
        self.listWidget_2.setStyleSheet("QWidget {\n"
"    border-radius: 8px;\n"
"    background-color: #a1e4ff;\n"
"}")
        self.listWidget_2.setObjectName("listWidget_2")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(795, 240, 201, 481))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.inputLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.inputLayout_2.setContentsMargins(0, 0, 0, 0)
        self.inputLayout_2.setSpacing(5)
        self.inputLayout_2.setObjectName("inputLayout_2")
        self.dragCoefficientLabel = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.dragCoefficientLabel.setFont(font)
        self.dragCoefficientLabel.setStyleSheet("QLabel {background-color: #a1e4ff;}")
        self.dragCoefficientLabel.setObjectName("dragCoefficientLabel")
        self.inputLayout_2.addWidget(self.dragCoefficientLabel)
        self.dragCoefficientSlider = QtWidgets.QSlider(self.verticalLayoutWidget_4)
        self.dragCoefficientSlider.setStyleSheet("QSlider::groove:horizontal {border: 1px solid #3256a8;\n"
"height: 8px;\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #85c8f2, stop: 1 #1293e3);}\n"
"\n"
"QSlider::handle:horizontal {border: 1px solid #3256a8;\n"
"background: #073191;\n"
"width: 10px;\n"
"height: 10px;\n"
"border-radius: 5px;}")
        self.dragCoefficientSlider.setOrientation(QtCore.Qt.Horizontal)
        self.dragCoefficientSlider.setObjectName("dragCoefficientSlider")
        self.inputLayout_2.addWidget(self.dragCoefficientSlider)
        self.dragCoefficientSliderLabel = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(10)
        self.dragCoefficientSliderLabel.setFont(font)
        self.dragCoefficientSliderLabel.setStyleSheet("QLabel {background-color: #a1e4ff;}")
        self.dragCoefficientSliderLabel.setText("")
        self.dragCoefficientSliderLabel.setObjectName("dragCoefficientSliderLabel")
        self.inputLayout_2.addWidget(self.dragCoefficientSliderLabel)
        self.dragCoefficientLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.dragCoefficientLineEdit.setFont(font)
        self.dragCoefficientLineEdit.setInputMask("")
        self.dragCoefficientLineEdit.setObjectName("dragCoefficientLineEdit")
        self.inputLayout_2.addWidget(self.dragCoefficientLineEdit)
        self.Line2_2 = QtWidgets.QFrame(self.verticalLayoutWidget_4)
        self.Line2_2.setStyleSheet("QFrame {\n"
"    background-color: #838285;\n"
"    min-height:1px;\n"
"    max-height:1px;\n"
"}")
        self.Line2_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.Line2_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Line2_2.setObjectName("Line2_2")
        self.inputLayout_2.addWidget(self.Line2_2)
        self.CSALabel = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.CSALabel.setFont(font)
        self.CSALabel.setStyleSheet("QLabel {background-color: #a1e4ff;}")
        self.CSALabel.setObjectName("CSALabel")
        self.inputLayout_2.addWidget(self.CSALabel)
        self.CSASlider = QtWidgets.QSlider(self.verticalLayoutWidget_4)
        self.CSASlider.setStyleSheet("QSlider::groove:horizontal {border: 1px solid #3256a8;\n"
"height: 8px;\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #85c8f2, stop: 1 #1293e3);}\n"
"\n"
"QSlider::handle:horizontal {border: 1px solid #3256a8;\n"
"background: #073191;\n"
"width: 10px;\n"
"height: 10px;\n"
"border-radius: 5px;}")
        self.CSASlider.setOrientation(QtCore.Qt.Horizontal)
        self.CSASlider.setObjectName("CSASlider")
        self.inputLayout_2.addWidget(self.CSASlider)
        self.CSASliderLabel = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(10)
        self.CSASliderLabel.setFont(font)
        self.CSASliderLabel.setStyleSheet("QLabel {background-color: #a1e4ff;}")
        self.CSASliderLabel.setText("")
        self.CSASliderLabel.setObjectName("CSASliderLabel")
        self.inputLayout_2.addWidget(self.CSASliderLabel)
        self.CSALineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.CSALineEdit.setFont(font)
        self.CSALineEdit.setObjectName("CSALineEdit")
        self.inputLayout_2.addWidget(self.CSALineEdit)
        self.Line3_2 = QtWidgets.QFrame(self.verticalLayoutWidget_4)
        self.Line3_2.setStyleSheet("QFrame {\n"
"    background-color: #838285;\n"
"    min-height:1px;\n"
"    max-height:1px;\n"
"}")
        self.Line3_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.Line3_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Line3_2.setObjectName("Line3_2")
        self.inputLayout_2.addWidget(self.Line3_2)
        self.airDensityLabel = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.airDensityLabel.setFont(font)
        self.airDensityLabel.setStyleSheet("QLabel {background-color: #a1e4ff;}")
        self.airDensityLabel.setObjectName("airDensityLabel")
        self.inputLayout_2.addWidget(self.airDensityLabel)
        self.airDensitySlider = QtWidgets.QSlider(self.verticalLayoutWidget_4)
        self.airDensitySlider.setStyleSheet("QSlider::groove:horizontal {border: 1px solid #3256a8;\n"
"height: 8px;\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #85c8f2, stop: 1 #1293e3);}\n"
"\n"
"QSlider::handle:horizontal {border: 1px solid #3256a8;\n"
"background: #073191;\n"
"width: 10px;\n"
"height: 10px;\n"
"border-radius: 5px;}")
        self.airDensitySlider.setOrientation(QtCore.Qt.Horizontal)
        self.airDensitySlider.setObjectName("airDensitySlider")
        self.inputLayout_2.addWidget(self.airDensitySlider)
        self.airDensitySliderLabel = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(10)
        self.airDensitySliderLabel.setFont(font)
        self.airDensitySliderLabel.setStyleSheet("QLabel {background-color: #a1e4ff;}")
        self.airDensitySliderLabel.setText("")
        self.airDensitySliderLabel.setObjectName("airDensitySliderLabel")
        self.inputLayout_2.addWidget(self.airDensitySliderLabel)
        self.airDensityLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.airDensityLineEdit.setFont(font)
        self.airDensityLineEdit.setObjectName("airDensityLineEdit")
        self.inputLayout_2.addWidget(self.airDensityLineEdit)
        self.Line4_2 = QtWidgets.QFrame(self.verticalLayoutWidget_4)
        self.Line4_2.setStyleSheet("QFrame {\n"
"    background-color: #838285;\n"
"    min-height:1px;\n"
"    max-height:1px;\n"
"}")
        self.Line4_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.Line4_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Line4_2.setObjectName("Line4_2")
        self.inputLayout_2.addWidget(self.Line4_2)
        self.massLabel = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.massLabel.setFont(font)
        self.massLabel.setStyleSheet("QLabel {background-color: #a1e4ff;}")
        self.massLabel.setObjectName("massLabel")
        self.inputLayout_2.addWidget(self.massLabel)
        self.massSlider = QtWidgets.QSlider(self.verticalLayoutWidget_4)
        self.massSlider.setStyleSheet("QSlider::groove:horizontal {border: 1px solid #3256a8;\n"
"height: 8px;\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #85c8f2, stop: 1 #1293e3);}\n"
"\n"
"QSlider::handle:horizontal {border: 1px solid #3256a8;\n"
"background: #073191;\n"
"width: 10px;\n"
"height: 10px;\n"
"border-radius: 5px;}")
        self.massSlider.setOrientation(QtCore.Qt.Horizontal)
        self.massSlider.setObjectName("massSlider")
        self.inputLayout_2.addWidget(self.massSlider)
        self.massSliderLabel = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(10)
        self.massSliderLabel.setFont(font)
        self.massSliderLabel.setStyleSheet("QLabel {background-color: #a1e4ff;}")
        self.massSliderLabel.setText("")
        self.massSliderLabel.setObjectName("massSliderLabel")
        self.inputLayout_2.addWidget(self.massSliderLabel)
        self.massLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.massLineEdit.setFont(font)
        self.massLineEdit.setObjectName("massLineEdit")
        self.inputLayout_2.addWidget(self.massLineEdit)
        self.inputLayout_2.setStretch(0, 1)
        self.inputLayout_2.setStretch(1, 1)
        self.inputLayout_2.setStretch(5, 1)
        self.inputLayout_2.setStretch(6, 2)
        self.inputLayout_2.setStretch(10, 1)
        self.inputLayout_2.setStretch(11, 1)
        self.inputLayout_2.setStretch(15, 1)
        self.inputLayout_2.setStretch(16, 1)
        self.noAirResLabel = QtWidgets.QLabel(self.frame)
        self.noAirResLabel.setGeometry(QtCore.QRect(90, 620, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.noAirResLabel.setFont(font)
        self.noAirResLabel.setStyleSheet("QLabel {background-color: #a1e4ff;}")
        self.noAirResLabel.setObjectName("noAirResLabel")
        self.airResLabel = QtWidgets.QLabel(self.frame)
        self.airResLabel.setGeometry(QtCore.QRect(360, 620, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.airResLabel.setFont(font)
        self.airResLabel.setStyleSheet("QLabel {background-color: #a1e4ff;}")
        self.airResLabel.setObjectName("airResLabel")
        self.rangeLabel_4 = QtWidgets.QLabel(self.frame)
        self.rangeLabel_4.setGeometry(QtCore.QRect(300, 650, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.rangeLabel_4.setFont(font)
        self.rangeLabel_4.setStyleSheet("QLabel {background-color: #a1e4ff;}")
        self.rangeLabel_4.setObjectName("rangeLabel_4")
        self.apogeeLabel_2 = QtWidgets.QLabel(self.frame)
        self.apogeeLabel_2.setGeometry(QtCore.QRect(300, 680, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.apogeeLabel_2.setFont(font)
        self.apogeeLabel_2.setStyleSheet("QLabel {background-color: #a1e4ff;}")
        self.apogeeLabel_2.setObjectName("apogeeLabel_2")
        self.flightTimeLabel_2 = QtWidgets.QLabel(self.frame)
        self.flightTimeLabel_2.setGeometry(QtCore.QRect(300, 710, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.flightTimeLabel_2.setFont(font)
        self.flightTimeLabel_2.setStyleSheet("QLabel {background-color: #a1e4ff;}")
        self.flightTimeLabel_2.setObjectName("flightTimeLabel_2")
        self.line_3 = QtWidgets.QFrame(self.frame)
        self.line_3.setGeometry(QtCore.QRect(280, 630, 3, 92))
        self.line_3.setStyleSheet("QFrame {background-color:  #838285; max-width: 1px; min-width:1px;}")
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.listWidget_3 = QtWidgets.QListWidget(self.frame)
        self.listWidget_3.setGeometry(QtCore.QRect(790, 150, 211, 71))
        self.listWidget_3.setStyleSheet("QWidget {\n"
"    border-radius: 8px;\n"
"    background-color: #a1e4ff;\n"
"}")
        self.listWidget_3.setObjectName("listWidget_3")
        self.airResFactorLabel = QtWidgets.QLabel(self.frame)
        self.airResFactorLabel.setGeometry(QtCore.QRect(800, 160, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.airResFactorLabel.setFont(font)
        self.airResFactorLabel.setStyleSheet("QLabel {background-color: #a1e4ff;}")
        self.airResFactorLabel.setObjectName("airResFactorLabel")
        self.listWidget_2.raise_()
        self.listWidget.raise_()
        self.backButton.raise_()
        self.verticalLayoutWidget.raise_()
        self.verticalLayoutWidget_3.raise_()
        self.infoButton.raise_()
        self.verticalLayoutWidget_2.raise_()
        self.analyticsListWidget.raise_()
        self.rangeLabel.raise_()
        self.apogeeLabel.raise_()
        self.flightTimeLabel.raise_()
        self.verticalLayoutWidget_4.raise_()
        self.noAirResLabel.raise_()
        self.airResLabel.raise_()
        self.rangeLabel_4.raise_()
        self.apogeeLabel_2.raise_()
        self.flightTimeLabel_2.raise_()
        self.line_3.raise_()
        self.listWidget_3.raise_()
        self.airResFactorLabel.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.backButton.setText(_translate("MainWindow", "Back"))
        self.textModeCheckBox.setText(_translate("MainWindow", "Manual Text Input"))
        self.launchSpeedLabel.setText(_translate("MainWindow", "Launch Speed /ms⁻¹"))
        self.launchSpeedLineEdit.setPlaceholderText(_translate("MainWindow", "Enter launch speed here"))
        self.label_3.setText(_translate("MainWindow", "Launch Angle /°"))
        self.launchAngleLineEdit.setPlaceholderText(_translate("MainWindow", "Enter launch angle here"))
        self.label_4.setText(_translate("MainWindow", "g /ms⁻²"))
        self.setgButton.setText(_translate("MainWindow", "Click to set g to 9.81ms⁻²"))
        self.gLineEdit.setPlaceholderText(_translate("MainWindow", "Enter g here"))
        self.label_5.setText(_translate("MainWindow", "Launch Height /m"))
        self.launchHeightLineEdit.setPlaceholderText(_translate("MainWindow", "Enter launch height here"))
        self.label_6.setText(_translate("MainWindow", "Time Step /ms"))
        self.timeStepLineEdit.setPlaceholderText(_translate("MainWindow", "Enter time step here"))
        self.infoButton.setText(_translate("MainWindow", "Info"))
        self.challengeTitleLabel.setText(_translate("MainWindow", "Challenge 9: Incorporating Air Resistance"))
        self.rangeLabel.setText(_translate("MainWindow", "Range /m:"))
        self.apogeeLabel.setText(_translate("MainWindow", "Apogee /m:"))
        self.flightTimeLabel.setText(_translate("MainWindow", "Time of Flight /s:"))
        self.dragCoefficientLabel.setText(_translate("MainWindow", "Drag Coefficient (Cd)"))
        self.dragCoefficientLineEdit.setPlaceholderText(_translate("MainWindow", "Enter drag coefficient here"))
        self.CSALabel.setText(_translate("MainWindow", "Cross Sectional Area /cm²"))
        self.CSALineEdit.setPlaceholderText(_translate("MainWindow", "Enter cross sectional area"))
        self.airDensityLabel.setText(_translate("MainWindow", "Air Density /kgm⁻³"))
        self.airDensityLineEdit.setPlaceholderText(_translate("MainWindow", "Enter air density here"))
        self.massLabel.setText(_translate("MainWindow", "Object Mass /kg"))
        self.massLineEdit.setPlaceholderText(_translate("MainWindow", "Enter object mass here"))
        self.noAirResLabel.setText(_translate("MainWindow", "No Air Resistance"))
        self.airResLabel.setText(_translate("MainWindow", "Air Resistance"))
        self.rangeLabel_4.setText(_translate("MainWindow", "Range /m:"))
        self.apogeeLabel_2.setText(_translate("MainWindow", "Apogee /m:"))
        self.flightTimeLabel_2.setText(_translate("MainWindow", "Time of Flight /s:"))
        self.airResFactorLabel.setText(_translate("MainWindow", "Air Resistance Factor:\n"
""))
